config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"items#index"
  resources :items do
    resources :comments, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image

  with_options presence: true do
    validates :name
    validates :description
    validates :url
    validates :image
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items
  has_many :comments

  with_options presence: true do
    validates :nickname
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,}+\z/i }, length: { minimum: 6 }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    comment = Comment.create(comment_params)
    redirect_to "/items/#{comment.item.id}"
  end

  private
  
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, item_id: params[:item_id])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :update, :destroy]

  def index
    @items = Item.includes(:user).order("created_at DESC")
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.create(item_params)
    if @item.save
      redirect_to root_path 
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to action: :show
    else
      render "edit"
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to root_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :image, :description, :url).merge(user_id: current_user.id)
  end

  def move_to_index
    @item = Item.find(params[:id])
    unless current_user.id == @item.user_id
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/items/_menu.html.erb
<%# メニューボタン %>
  <div class="openbtn"><span></span><span></span><span></span></div>

  <nav id="g-nav">
  <div id="g-nav-list">
    <ul class="menu-contents">
      <%= link_to 'TOP', '/', class:"menu-content" %>
      <%= link_to 'POST', new_item_path, class:"menu-content" %>
    <% if user_signed_in? %>
      <%= link_to 'LOGOUT', destroy_user_session_path, method: :delete, class:"menu-content" %>
    <% else %>
      <%= link_to 'LOGIN', new_user_session_path, class:"menu-content" %>
      <%= link_to 'SIGNUP', new_user_registration_path, class:"menu-content" %>
    <% end %>
    </ul>
  </div>
  </nav>
 <%# /メニューボタン %>

app/views/items/edit.html.erb
<div class='main'>

<%= render "menu" %>


<div class="item-new">
<h1 class="new-top">POST</h1>
<%= form_with model: @item, class: 'form', local: true do |f| %>
  <div>
  <ul>
    <li><%= f.text_field :name, class: 'text-new', placeholder: 'name' %></li>
    <li><%= f.text_field :description, class: 'text-new', placeholder: 'description' %></li>
    <li><%= f.text_field :url, class: 'text-new', placeholder: 'url' %></li>
    <li><label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label></li>
  </div>
  </ul>
  <%= f.submit 'SEND', class:"new-submit" %>
<% end %>
</div>

</div>

app/views/items/index.html.erb
<div class='main'>

<script src="https://rawgit.com/kimmobrunfeldt/progressbar.js/master/dist/progressbar.min.js"></script>

<div id="splash">
  <div id="splash_text"></div>
<!--/splash--></div>

<%= render "menu" %>

  <%# スライドショー %>

  <div id="slider">
  <!--/slider-->
    <h2 class='slider-title'>
      <%= image_tag "title2.png" %>
    </h2>
  </div>

  <%# /スライドショー %>

  <h1 class="guide">POSTS LIST</h1>

  <%# ギャラリー表示 %>
  
    <ul class="gallery">
      <li><% @items.each do |item| %>
        <%= link_to item_path(item.id) do %>
          <div class="fadeUpTrigger">
          <%= image_tag item.image, class: "item-image" %>
          <span class='item-name'>
            <%= item.name %>
          </span>
          </div>
        <% end %>
      <% end %>
      </li>
    </ul>
  
  <%# /ギャラリー表示 %>

</div>

app/views/items/new.html.erb
<div class='main'>

<%= render "menu" %>


<div class="item-new">
<h1 class="new-top">POST</h1>
<%= form_with model: @item, class: 'form', local: true do |f| %>
  <div>
  <ul>
    <div class="new-holder">NAME</div>
    <li><%= f.text_field :name, class: 'text-new' %></li>
    <div class="new-holder">DESCRIPTION</div>
    <li><%= f.text_field :description, class: 'text-new' %></li>
    <div class="new-holder">URL</div>
    <li><%= f.text_field :url, class: 'text-new' %></li>
    
    <li><label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label></li>
  </div>
  </ul>
  <%= f.submit 'SEND', class:"new-submit" %>
<% end %>
</div>

</div>

app/views/items/show.html.erb
<div class='main'>

<%= render "menu" %>

<%# 商品の概要 %>
<div class="item-show">

  <br>

  <div>
    <%= image_tag @item.image ,class:"item-show-image" %>
  </div>

  <br>

  <div>
    <h4>タイトル</h4>
    <div><%= @item.name %></div>
    <br>
    <h4>詳細</h4>
    <div><%= @item.description %></div>
    <br>
    <h4>投稿者</h4>
    <div><%= @item.user.nickname %></div>
    <br>
    <h4>URL</h4>
    <div><%= @item.url %>
  </div>

  <br>

  <% if user_signed_in? && current_user.id == @item.user_id %>
    <%= link_to "編集", edit_item_path, method: :get %>
    <p class="or-text">or</p>
    <%= link_to "削除", item_path, method: :delete %>
  <% end %>

</div>
<%# /商品の概要 %>

<%# コメント機能 %>
  <div class="container">
    <% if user_signed_in? %>
      <%= form_with(model: [@item, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= comment.user.nickname %>：</strong>
          <%= comment.text %>
        </p>
      <% end %>
    </div>
  </div>
<%# /コメント機能 %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teatime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>